export interface IjQuery{
    ready(fn);
    html(arg);
    text(arg);
    css(arg);
    addClass(arg);
    removeClass(arg);
    toggleClass(arg);
    attr(name, arg);
    trim(str);
    trimAll(str);
    val(arg);
    after(arg);
    before(arg);
    prepend(arg);
    append(arg);
    remove(arg);
    height(arg);
    width(arg);
    innerHeight(arg);
    innerWidth(arg);
    outerHeight(arg);
    outerWidth(arg);
    click(fun);
    dblclick(fun);
    mouseup(fun);
    focus(fun);
    blur(fun);
    select(fun);
    change(fun);
    onload(fun);
    unload(fun);
    mouseover(fun);
    mouseout(fun);
    hover(fun1, fun2);
    mouseenter(fun);
    mouseleave(fun);
    keypress(fun);
    keydown(fun);
    keyup(fun);
    submit(fun);
    resize(fun);
    scroll(fun);
    show(time, callback);
    hide(time, callback);
    animate(json, interval, sp, fn);
    animateRun(obj, json, interval, sp, fn);
    stop();
    empty();
    each(object, callback);
    parents();
    parent();
    children(num);
    siblings(arg);
    next();
    nextAll();
    prev();
    prevAll();
    first();
    last();
    eq(index);
    filter(arg);
    not(arg);
}